### ISSUE TITLE
Maximum call stack size exceeded - Using the Foundation set of ALICE Bot

### ISSUE THREAD

**Issue by gritsa** [gleuch/aiml-high#3]
Hi,

I am doing a very simple and straightforward instantiation of the original ALICE Bot AIML files from https://code.google.com/archive/p/aiml-en-us-foundation-alice/downloads and it fails with the below error. If I create my own fresh AIML files (which are very small and for test purposes only) it works fine. But I am concerned if this module can ever handle a large bot like the Foundation AIML files.

I get the following error with Foundation ALICE bot files:

`/home/abhishek/Dropbox/Projects/aiml/node_modules/aiml-high/aiml-high.js:91
    var cleanedStr = str.replace(/\r\n/gi, '');
                         ^

RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at cleanStringFormatCharacters (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:91:26)
    at resolveSpecialNodes (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:416:16)
    at findFinalTextInTemplateNode (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:228:17)
    at travereseThroughDomToFindMatchingPattern (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:140:36)
    at travereseThroughDomToFindMatchingPattern (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:126:22)
    at findCorrectCategory (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:420:12)
    at findFinalTextInTemplateNode (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:215:28)
    at findFinalTextInTemplateNode (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:202:24)
    at travereseThroughDomToFindMatchingPattern (/home/abhishek/Dropbox/Projects/shaniaAI/node_modules/aiml-high/aiml-high.js:140:36)

npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--stack-size=1000000"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! shaniaAI@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the shaniaAI@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shaniaAI package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
`

**Comment by gritsa** [comment]
I missed mentioning - I have tried increasing the stack size and I wouldn't be tempted to say it works (it basically answers like one simple question and then fails at the next with the same error as above)
Plus I dont think increasing the stack size would be a good solution.

Ohh and I also tried wrapping it into a setImmediate and setTimeout, didn't work. Maybe I am doing something wrong? Any help would be appreciated.

**Comment by mariohmol** [comment]
Cool!! I started doing the same yesterday! =) 

So, there is a bunch of aiml files there.. did u try one file or all at once?

**Comment by gritsa** [comment]
Hey mariohmol!

I tried a single small file first and that worked. I then tried a single large file (> 700KB), and it didn't work. Loading all of the files obviously it didn't work. I would love to see if I can contribute in fixing this issue but I am not sure about where the issue could be, and I first want to ensure its not an environment issue that I am struggling with.

Let me know if you can also reproduce it and you know off the top of your head what the issue is. I couldn't get it to work by increasing the stack size which is a bummer. If that works I think we can live with it.

Let me know what you think!

**Comment by mariohmol** [comment]
I see.. actualy now i'm testing all ailm that works with nodejs.. i'm now giving a shot in https://github.com/aichaos/rivescript-js

**Comment by gleuch** [comment]
@mariohmol highly recommend rivescript. started w/ aiml for our project but switched to rivescript so it would be easier for writers to format conversations. (markdown-like fomatting > XML formatting)

**Comment by gleuch** [comment]
@gritsa i have not tested in high performance environments or with large sets of conversation markup. 

i do wonder if there is something happening w/i your markup, like an infinite redirect or such.

if you want to test it more and submit patches via pull requests, happy to merge them in and uptick version for npm.

**Comment by gritsa** [comment]
@greg the set of AIML I am using is the foundation ALICE aiml files. I ran
them with a C# interpreter and that worked just fine, which is what leading
me to believe that Node is the issue here.

Abhishek Chatterjee,
_Gritsa Technologies_

P (+1) 424-250-2424
C (+91) 965-020-9304
O (+91) 120-421-8556

**Comment by mariohmol** [comment]
@gritsa  here is a example with alice and rivescript https://github.com/aichaos/alice-benchmarks

I just started using rivescript and i'm already collaboration in this project.. @gleuch helped a lot as well.. so maybe we can join efforts in same project to make that bigger
